### ISSUE TITLE
[Chore] jest, 바벨, jest를 위한 웹팩 설정 설치, config 설정

### ISSUE THREAD

**Issue by hongjw030** [hongjw030/introspection-helper#20]
단위 테스트 도입을 위해 jest를 활용하기로 결정. jest는 node.js 환경에서 실행되지만, 웹팩과 바벨을 통해 브라우저 단에서도 활용이 가능하며 이를 통해 익스텐션 프로그램에서도 적용 가능하다고 한다.

## Todo
- [ ] jest, barbel, webpack 설치
- [ ] webpack.config 설정
- [ ] jest를 위한 test 폴더 생성
